---
- name: update apt cache if needed
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: Upgrade APT to the latest packages
  apt:
    upgrade: dist

- name: Autoremove unused packages
  apt:
    autoremove: yes
